

AddCSLuaFile()

game.AddAmmoType {
	name = "rwby_dust",
	dmgtype = DMG_BULLET,
	tracer = TRACER_LINE,
	plydmg = 0,
	npcdmg = 0,
	force = 2000,
	minsplash = 10,
	maxsplash = 15
}
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")
print("RWBY: AUTORUN SCRIPT IS RUNNING")